name: "Tether Agent"
description: "A tether agent. For Home Assistant."
version: "latest"
slug: "tether-agent"
init: false
hassio_role: "manager"
hassio_api: true
homeassistant_api: true
arch:
  - aarch64
  - amd64
image: randomstudiotools/hass-tether-agent-{arch}

options:
  host: ""
  port: "1885"
  username: "tether"
  password: "sp_ceB0ss!"
schema:
  host: str
  port: str
  username: str
  password: str
