name: "Tether Broker"
description: "A tether broker. Hosted within Home Assistant."
version: "latest"
slug: "tether-broker"
init: false
hassio_role: "manager"
hassio_api: true
homeassistant_api: true
arch:
  - aarch64
  - amd64

ports:
  1883/tcp: 1885
image: randomstudiotools/tether-broker
