name: "Tether Agent"
description: "A tether agent. For Home Assistant."
version: "1.0.4"
slug: "tether-agent"
init: false
hassio_role: "homeassistant"
hassio_api: true
homeassistant_api: true
ingress: true
arch:
  - aarch64

options:
  host: ""
  port: "1883"
  username: "tether"
  password: ""
schema:
  host: str
  port: str
  username: str
  password: str
